/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Actores.CentralMascota;
import Actores.Mascota;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo
 */
public class frmagg_mascota2 extends javax.swing.JFrame {

    private Mascota mascota;
    private CentralMascota cm;
    private frmgestion_mascotas frmMascotas;

    /**
     * Creates new form frmagg_mascota2
     */
    public frmagg_mascota2() {
        initComponents();
    }

    public frmagg_mascota2(Mascota mascota, CentralMascota cm, frmgestion_mascotas frmMascotas) {
        initComponents();
        this.Grupo_Mascotas.add(this.RB_Alcomienzo);
        this.Grupo_Mascotas.add(this.RB_AlFinal);
        this.Grupo_Mascotas.add(this.RB_AgregarAntesDe);
        this.Grupo_Mascotas.add(this.RB_Agregardespuesconcodigo);
        this.mascota = mascota;
        this.cm = cm;
        this.frmMascotas = frmMascotas;
        super.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_Mascotas = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        RB_Alcomienzo = new javax.swing.JRadioButton();
        RB_AlFinal = new javax.swing.JRadioButton();
        RB_AgregarAntesDe = new javax.swing.JRadioButton();
        RB_Agregardespuesconcodigo = new javax.swing.JRadioButton();
        txt_Mascota_codigoAntes = new javax.swing.JTextField();
        txt_Mascota_CodigoDespues = new javax.swing.JTextField();
        btnCancelar_AgregarMascota = new javax.swing.JButton();
        btn_AgregarMascota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        RB_Alcomienzo.setText("Agregar al Inicio");

        RB_AlFinal.setText("Agregar al Final");

        RB_AgregarAntesDe.setText("Antes de ");

        RB_Agregardespuesconcodigo.setText("Despues de");

        btnCancelar_AgregarMascota.setText("Cancelar");

        btn_AgregarMascota.setText("Finalizar");
        btn_AgregarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RB_Alcomienzo)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RB_AgregarAntesDe)
                        .addComponent(RB_AlFinal)
                        .addComponent(RB_Agregardespuesconcodigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Mascota_CodigoDespues, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(txt_Mascota_codigoAntes))
                .addGap(66, 66, 66))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnCancelar_AgregarMascota)
                .addGap(75, 75, 75)
                .addComponent(btn_AgregarMascota)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(RB_Alcomienzo)
                .addGap(18, 18, 18)
                .addComponent(RB_AlFinal)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_AgregarAntesDe)
                    .addComponent(txt_Mascota_codigoAntes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_Agregardespuesconcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Mascota_CodigoDespues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar_AgregarMascota)
                    .addComponent(btn_AgregarMascota))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarMascotaActionPerformed
        // TODO add your handling code here:
         if (this.RB_Alcomienzo.isSelected())
    {
      this.cm.insertarAlComienzo(this.mascota);
      JOptionPane.showMessageDialog(this.rootPane, "La mascota ha sido agregada");
      System.out.println("------------------------");
      this.cm.mostrarMascotas();
    }
    if (this.RB_AlFinal.isSelected())
    {
      this.cm.insertarUltimo(this.mascota);
      JOptionPane.showMessageDialog(this.rootPane, "La mascota ha sido agregada");
      System.out.println("------------------------");
      this.cm.mostrarMascotas();
    }
    if (this.RB_AgregarAntesDe.isSelected()) {
      if (this.cm.buscarMascota(Integer.parseInt(this.txt_Mascota_codigoAntes.getText())) != null)
      {
        this.cm.insertarantesde(Integer.parseInt(this.txt_Mascota_codigoAntes.getText()), this.mascota);
        JOptionPane.showMessageDialog(this.rootPane, "La mascota ha sido agregada");
        System.out.println("------------------------");
        this.cm.mostrarMascotas();
      }
      else
      {
        JOptionPane.showMessageDialog(this.rootPane, "La mascota que ha referenciado no existe");
      }
    }
    if (this.RB_Agregardespuesconcodigo.isSelected())
    {
      if (this.cm.buscarMascota(Integer.parseInt(this.txt_Mascota_CodigoDespues.getText())) != null)
      {
        this.cm.insertarDespuesDe(Integer.parseInt(this.txt_Mascota_CodigoDespues.getText()), this.mascota);
        JOptionPane.showMessageDialog(this.rootPane, "La mascota ha sido agregada");
        System.out.println("------------------------");
        this.cm.mostrarMascotas();
      }
      else
      {
        JOptionPane.showMessageDialog(this.rootPane, "La mascota que ha referenciado no existe");
      }
      System.out.println("------------------------");
    }
    this.frmMascotas.setVisible(true);
    this.frmMascotas.llenarMascotas();
    this.cm.mostrarMascotas();
    this.frmMascotas.setVisible(true);
    dispose();
    }//GEN-LAST:event_btn_AgregarMascotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmagg_mascota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmagg_mascota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmagg_mascota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmagg_mascota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmagg_mascota2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo_Mascotas;
    private javax.swing.JRadioButton RB_AgregarAntesDe;
    private javax.swing.JRadioButton RB_Agregardespuesconcodigo;
    private javax.swing.JRadioButton RB_AlFinal;
    private javax.swing.JRadioButton RB_Alcomienzo;
    private javax.swing.JButton btnCancelar_AgregarMascota;
    private javax.swing.JButton btn_AgregarMascota;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JTextField txt_Mascota_CodigoDespues;
    private javax.swing.JTextField txt_Mascota_codigoAntes;
    // End of variables declaration//GEN-END:variables
}
