/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Actores.*;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JInternalFrame;

/**
 *
 * @author Camilo
 */
public class frmmenu_principal extends javax.swing.JFrame {

    /**
     * Creates new form frmmenu_principal
     */
    Scanner sc = new Scanner(System.in);
    frmgestion_clientes form;
    frmgestion_inventario frmInventario;
    frm_RedReferencia red;
    CentralRedReferencia r;

    private JInternalFrame escritorio;

    public frmmenu_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.form = new frmgestion_clientes(new CentralCliente());
        this.frmInventario = new frmgestion_inventario(new CentralInventario());
        this.red = new frm_RedReferencia(new CentralClinica());
        this.setTitle("Pagina Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        btngestion_clientes = new javax.swing.JButton();
        btnestionInventario = new javax.swing.JButton();
        btngestionRedReferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        btngestion_clientes.setText("Gestionar Clientes");
        btngestion_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestion_clientesActionPerformed(evt);
            }
        });

        btnestionInventario.setText("Gestión de Inventario");
        btnestionInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnestionInventarioActionPerformed(evt);
            }
        });

        btngestionRedReferencia.setText("Gestión Red de referencia");
        btngestionRedReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestionRedReferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btngestion_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnestionInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngestionRedReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btngestion_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnestionInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btngestionRedReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngestion_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestion_clientesActionPerformed

        // TODO add your handling code here:
        this.form.setLocationRelativeTo(null);
        this.form.setVisible(true);
        this.form.setTitle("Gestión de Clientes");
        this.form.show();

    }//GEN-LAST:event_btngestion_clientesActionPerformed

    private void btnestionInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnestionInventarioActionPerformed
        // TODO add your handling code here:
        this.frmInventario.setLocationRelativeTo(null);
        this.frmInventario.setVisible(true);
        this.frmInventario.setTitle("Gestión de Inventario");
        this.frmInventario.show();
    }//GEN-LAST:event_btnestionInventarioActionPerformed

    private void btngestionRedReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionRedReferenciaActionPerformed
        // TODO add your handling code here:
        
       this.red.setLocationRelativeTo(null);
       this.red.setVisible(true);      
       this.red.setTitle("Red de Referencia");
       this.red.show();       

    }//GEN-LAST:event_btngestionRedReferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmenu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmenu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmenu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmenu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmenu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnestionInventario;
    private javax.swing.JButton btngestionRedReferencia;
    private javax.swing.JButton btngestion_clientes;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
